In [2]:
from sklearn import tree
from sklearn.svm import SVC
from sklearn.linear_model import Perceptron
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn import datasets
import numpy as np
from sklearn import datasets

In [3]:
#load data
digits=datasets.load_digits()

In [4]:
digits.images=digits.images.reshape(digits.images.shape[0],digits.images.shape[1]*digits.images.shape[2])

In [5]:
#matrix dimensions
print(digits.images.shape)

(1797, 64)


In [6]:
#printing features and labels 
print(digits.images)
print(digits.target)

[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]]
[0 1 2 ..., 8 9 8]


In [7]:
#data dimensions
print(digits.images.shape)
print(digits.target.shape)

(1797, 64)
(1797,)


In [8]:
#now we have data, we need to split this whole chunk of data in to training and testing data set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.images,digits.target,test_size=0.25)

In [9]:
#importing classifier
from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier(n_neighbors=3).fit(x_train,y_train)

In [10]:
#testing the model
from sklearn.metrics import accuracy_score
print("accuracy found is")
print(accuracy_score(y_test,clf.predict(x_test)))

accuracy found is
0.995555555556


In [11]:
#adding classifiers 
clf_KNN=KNeighborsClassifier()
clf_svm = SVC()
clf_perceptron = Perceptron()
clf_tree = tree.DecisionTreeClassifier()
clf_gnb = GaussianNB()

#train classifiers
clf_tree.fit(x_train, y_train)
clf_svm.fit(x_train, y_train)
clf_perceptron.fit(x_train, y_train)
clf_KNN.fit(x_train, y_train)
clf_gnb.fit(x_train, y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


GaussianNB(priors=None)

In [14]:
# Testing using the same data
pred_tree = clf_tree.predict(x_test)
acc_tree = accuracy_score(y_test, pred_tree) * 100
print('Accuracy for DecisionTree: {}'.format(acc_tree))

pred_svm = clf_svm.predict(x_test)
acc_svm = accuracy_score(y_test, pred_svm) * 100
print('Accuracy for SVM: {}'.format(acc_svm))

pred_per = clf_perceptron.predict(x_test)
acc_per = accuracy_score(y_test, pred_per) * 100
print('Accuracy for perceptron: {}'.format(acc_per))

pred_KNN = clf_KNN.predict(x_test)
acc_KNN = accuracy_score(y_test, pred_KNN) * 100
print('Accuracy for KNN: {}'.format(acc_KNN))

pred_gnb = clf_gnb.predict(x_test)
acc_gnb = accuracy_score(y_test, pred_gnb) * 100
print('Accuracy for gnb: {}'.format(acc_gnb))

# The best classifier from svm, per, KNN
index = np.argmax([acc_tree, acc_svm, acc_per, acc_KNN, acc_gnb])
index2 = np.argmin([acc_tree, acc_svm, acc_per, acc_KNN, acc_gnb])

classifiers = {0: 'Tree', 1: 'SVM', 2: 'Perceptron', 3: 'KNN', 4: 'gnb'}
print('Best classifier is {}'.format(classifiers[index]))
print('Worst classifier is {}'.format(classifiers[index2]))

Accuracy for DecisionTree: 83.33333333333334
Accuracy for SVM: 38.0
Accuracy for perceptron: 86.66666666666667
Accuracy for KNN: 99.33333333333333
Accuracy for gnb: 79.77777777777779
Best classifier is KNN
Worst classifier is SVM


In [23]:
#Kfold cross validation
from sklearn.model_selection import KFold

In [27]:
kf = KFold(n_splits=8, shuffle=True)

X = ["a", "b", "c", "d", "e", "f", "g", "h"]
for train, test in kf.split(X):
    print("%s %s" % (train, test))

[1 2 3 4 5 6 7] [0]
[0 2 3 4 5 6 7] [1]
[0 1 2 4 5 6 7] [3]
[0 1 2 3 4 6 7] [5]
[0 1 2 3 4 5 7] [6]
[0 1 3 4 5 6 7] [2]
[0 1 2 3 4 5 6] [7]
[0 1 2 3 5 6 7] [4]
