In [2]:
# BIBLIOTECA NUMPY

In [4]:
import numpy 

In [5]:
a = numpy.array([10,20,30,40])
print(a)

[10 20 30 40]


In [7]:
mat = numpy.array([[10,20],[30,40]])
print(mat)


[[10 20]
 [30 40]]


In [8]:
print(mat[-1][-1])


40


In [11]:
print(mat[1])


[30 40]


In [12]:
print(mat[:,0])


[10 30]


In [13]:
mat.transpose()


array([[10, 30],
       [20, 40]])

# matrix operations


In [14]:
m1 = numpy.array([[10,20],[50,60]])
m2 = numpy.array([[22,45],[12,9]])

print(m1+m2)


[[32 65]
 [62 69]]


In [17]:
print(m1-m2)


[[-12 -25]
 [ 38  51]]


In [18]:
print(m1*m2)


[[220 900]
 [600 540]]


In [21]:
print(m1/m2)


[[ 0.45454545  0.44444444]
 [ 4.16666667  6.66666667]]


In [22]:
m1.sum()


140

In [23]:
m2.argmax()


1

In [24]:
m2.argmin()

3

In [27]:
print(m2)
m2.diagonal()


[[22 45]
 [12  9]]


array([22,  9])