In [1]:
import matplotlib

In [2]:
import numpy as np

In [3]:
from random import *

In [4]:
#Dans la zone étudiée, on estime qu'il y a 4 fois plus de gazelles que de lions/lionnes
#Ainsi, par exemple, sur une zone matrice de 25 "cases" on comptera 12 gazelles, 3 lions/lionnes et donc 10 cases vides
#La gazelle prend comme valeur 1
#La meute de lionne prend la valeur 2
#Le lion prend la valeur 3
#Une case vide prend la valeur 0

In [5]:
#Création d'une matrice d composée uniquement de 0 représentant une case vide
#matrice composée de a lignes et b colonnes (a et b étant des valeurs que l'on peut modifier directement dans le programme)
a=10
b=10
d = np.zeros((a,b))
d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
#Création d'une liste M avec toutes les positions possibles de la matrice d 
M=[]
for k in range (0,a) : 
    for i in range (0,b) : 
        M.append([k,i])

In [7]:
M

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [0, 5],
 [0, 6],
 [0, 7],
 [0, 8],
 [0, 9],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [1, 4],
 [1, 5],
 [1, 6],
 [1, 7],
 [1, 8],
 [1, 9],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [2, 4],
 [2, 5],
 [2, 6],
 [2, 7],
 [2, 8],
 [2, 9],
 [3, 0],
 [3, 1],
 [3, 2],
 [3, 3],
 [3, 4],
 [3, 5],
 [3, 6],
 [3, 7],
 [3, 8],
 [3, 9],
 [4, 0],
 [4, 1],
 [4, 2],
 [4, 3],
 [4, 4],
 [4, 5],
 [4, 6],
 [4, 7],
 [4, 8],
 [4, 9],
 [5, 0],
 [5, 1],
 [5, 2],
 [5, 3],
 [5, 4],
 [5, 5],
 [5, 6],
 [5, 7],
 [5, 8],
 [5, 9],
 [6, 0],
 [6, 1],
 [6, 2],
 [6, 3],
 [6, 4],
 [6, 5],
 [6, 6],
 [6, 7],
 [6, 8],
 [6, 9],
 [7, 0],
 [7, 1],
 [7, 2],
 [7, 3],
 [7, 4],
 [7, 5],
 [7, 6],
 [7, 7],
 [7, 8],
 [7, 9],
 [8, 0],
 [8, 1],
 [8, 2],
 [8, 3],
 [8, 4],
 [8, 5],
 [8, 6],
 [8, 7],
 [8, 8],
 [8, 9],
 [9, 0],
 [9, 1],
 [9, 2],
 [9, 3],
 [9, 4],
 [9, 5],
 [9, 6],
 [9, 7],
 [9, 8],
 [9, 9]]

In [8]:
indices = np.random.choice(np.arange(len(M)), a*b, replace=False)


In [9]:
#Création d'un tableau "positions" représentant toutes les positions de la matrice "d" dans le désordre 
positions = np.array(M)[indices]

In [10]:
positions

array([[4, 1],
       [2, 8],
       [9, 2],
       [0, 8],
       [1, 5],
       [5, 5],
       [1, 3],
       [0, 9],
       [9, 6],
       [0, 0],
       [0, 5],
       [3, 7],
       [3, 6],
       [0, 6],
       [7, 8],
       [5, 3],
       [5, 2],
       [6, 8],
       [9, 5],
       [3, 2],
       [2, 6],
       [8, 9],
       [3, 4],
       [1, 6],
       [2, 0],
       [4, 6],
       [6, 1],
       [7, 9],
       [7, 7],
       [1, 4],
       [7, 6],
       [9, 1],
       [1, 0],
       [9, 3],
       [3, 0],
       [2, 5],
       [2, 9],
       [4, 9],
       [0, 7],
       [9, 0],
       [6, 6],
       [7, 5],
       [6, 0],
       [6, 2],
       [8, 6],
       [6, 5],
       [2, 7],
       [1, 9],
       [1, 1],
       [8, 5],
       [9, 7],
       [3, 9],
       [0, 3],
       [7, 2],
       [2, 4],
       [9, 4],
       [4, 4],
       [2, 1],
       [5, 8],
       [4, 8],
       [6, 7],
       [8, 4],
       [6, 3],
       [4, 7],
       [3, 1],
       [4, 3],
       [5,

In [11]:
#On remplace maintenant dans la matrice d, certaines cases vides par une case représentant une gazelle dont la valeur est
#égale à 1. On estime qu'il faut remplir la matrice à 48% de gazelles
n = len(positions)
c=0
for k in range (0,n) :
    position = positions[k]
    print(position)
    value = d[position[0],position[1]]
    if value==1 : 
        c=c+1
q=0
while c<0.48*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==1 : 
        q=q+1
    else : 
        d[position[0],position[1]] = 1
        print("En {} on a mis une gazelle".format(position))
        c = c+1
        q=q+1

[4 1]
[2 8]
[9 2]
[0 8]
[1 5]
[5 5]
[1 3]
[0 9]
[9 6]
[0 0]
[0 5]
[3 7]
[3 6]
[0 6]
[7 8]
[5 3]
[5 2]
[6 8]
[9 5]
[3 2]
[2 6]
[8 9]
[3 4]
[1 6]
[2 0]
[4 6]
[6 1]
[7 9]
[7 7]
[1 4]
[7 6]
[9 1]
[1 0]
[9 3]
[3 0]
[2 5]
[2 9]
[4 9]
[0 7]
[9 0]
[6 6]
[7 5]
[6 0]
[6 2]
[8 6]
[6 5]
[2 7]
[1 9]
[1 1]
[8 5]
[9 7]
[3 9]
[0 3]
[7 2]
[2 4]
[9 4]
[4 4]
[2 1]
[5 8]
[4 8]
[6 7]
[8 4]
[6 3]
[4 7]
[3 1]
[4 3]
[5 1]
[3 3]
[7 4]
[8 3]
[5 4]
[8 8]
[8 1]
[5 6]
[3 8]
[2 3]
[7 0]
[8 7]
[5 9]
[5 0]
[1 2]
[4 2]
[9 9]
[8 2]
[7 1]
[4 5]
[0 1]
[1 8]
[9 8]
[7 3]
[6 4]
[2 2]
[0 2]
[8 0]
[3 5]
[5 7]
[0 4]
[1 7]
[4 0]
[6 9]
En [4 1] on a mis une gazelle
En [2 8] on a mis une gazelle
En [9 2] on a mis une gazelle
En [0 8] on a mis une gazelle
En [1 5] on a mis une gazelle
En [5 5] on a mis une gazelle
En [1 3] on a mis une gazelle
En [0 9] on a mis une gazelle
En [9 6] on a mis une gazelle
En [0 0] on a mis une gazelle
En [0 5] on a mis une gazelle
En [3 7] on a mis une gazelle
En [3 6] on a mis une gazelle
En [0 6] o

In [12]:
#On remplace maintenant quelques cases vide par une case représentant les lions. 
#On estime qu'ils sont présents à 4%
n = len(positions)
x=0
for k in range (0,n) :
    position = positions[k]
    print(position)
    value = d[position[0],position[1]]
    if value==2 : 
        x=x+1
q=0
while x<0.04*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==2 : 
        q=q+1
    elif value == 1 :
        q=q+1
    else : 
        d[position[0],position[1]] = 2
        print("En {} on a mis un lion".format(position))
        x = x+1
        q=q+1

[4 1]
[2 8]
[9 2]
[0 8]
[1 5]
[5 5]
[1 3]
[0 9]
[9 6]
[0 0]
[0 5]
[3 7]
[3 6]
[0 6]
[7 8]
[5 3]
[5 2]
[6 8]
[9 5]
[3 2]
[2 6]
[8 9]
[3 4]
[1 6]
[2 0]
[4 6]
[6 1]
[7 9]
[7 7]
[1 4]
[7 6]
[9 1]
[1 0]
[9 3]
[3 0]
[2 5]
[2 9]
[4 9]
[0 7]
[9 0]
[6 6]
[7 5]
[6 0]
[6 2]
[8 6]
[6 5]
[2 7]
[1 9]
[1 1]
[8 5]
[9 7]
[3 9]
[0 3]
[7 2]
[2 4]
[9 4]
[4 4]
[2 1]
[5 8]
[4 8]
[6 7]
[8 4]
[6 3]
[4 7]
[3 1]
[4 3]
[5 1]
[3 3]
[7 4]
[8 3]
[5 4]
[8 8]
[8 1]
[5 6]
[3 8]
[2 3]
[7 0]
[8 7]
[5 9]
[5 0]
[1 2]
[4 2]
[9 9]
[8 2]
[7 1]
[4 5]
[0 1]
[1 8]
[9 8]
[7 3]
[6 4]
[2 2]
[0 2]
[8 0]
[3 5]
[5 7]
[0 4]
[1 7]
[4 0]
[6 9]
En [1 1] on a mis un lion
En [8 5] on a mis un lion
En [9 7] on a mis un lion
En [3 9] on a mis un lion


In [13]:
#On rajoute maintenant les meutes de lionnes éstimées à 8%
n = len(positions)
y=0
for k in range (0,n) :
    position = positions[k]
    value = d[position[0],position[1]]
    if value==3 : 
        y=y+1
q=0
while y<0.08*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value == 3 : 
        q=q+1
    elif value == 1 :
        q=q+1
    elif value == 2 :
        q=q+1
    else : 
        d[position[0],position[1]] = 3
        print("En {} on a mis une lionne".format(position))
        y = y+1
        q=q+1

En [0 3] on a mis une lionne
En [7 2] on a mis une lionne
En [2 4] on a mis une lionne
En [9 4] on a mis une lionne
En [4 4] on a mis une lionne
En [2 1] on a mis une lionne
En [5 8] on a mis une lionne
En [4 8] on a mis une lionne


In [14]:
#On affiche maintenant la matrice d avec toute la population placée aléatoirement. 
d

array([[ 1.,  0.,  0.,  3.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.],
       [ 1.,  3.,  0.,  0.,  3.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  2.],
       [ 0.,  1.,  0.,  0.,  3.,  0.,  1.,  0.,  3.,  1.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  3.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  3.,  1.,  1.,  2.,  0.,  0.]])

In [15]:
d.size

100

In [16]:
len(np.where(d == 1.)[0])

48

In [17]:
len(np.where(d == 2.)[0])

4

In [18]:
len(np.where(d == 3.)[0])

8

In [19]:
#On s'interesse aux voisins de chaque case
def voisins(x,y) : 
    """Renvoie aléatoirement un des voisins de (x,y) dans la matrice d en faisant attention aux coins/bords"""
    L = []

    #coin supérieur gauche
    if x == 0 and y == 0 : 
        L.append(d[(x+1),y])
        L.append(d[x,(y+1)])
    
    #coin supérieur droit
    elif x == 0 and y == (b-1) : 
        L.append(d[(x+1),y])
        L.append(d[x,(y-1)])
    
    #coin inférieur gauche
    elif x == (a-1) and y == 0 : 
        L.append(d[x,(y+1)])
        L.append(d[(x-1),y])
    
    #coin inférieur droit
    elif x == (a-1) and y == (b-1) : 
        L.append(d[(x-1),y])
        L.append(d[x,(y-1)])
    
    #ligne du haut
    elif x == 0 and y != 0:
        L.append(d[(x,(y-1))])
        L.append(d[(x+1),y])
        L.append(d[x,(y+1)])
        
    #ligne de gauche
    elif x !=0 and y == 0 : 
        L.append(d[(x-1),y])
        L.append(d[(x+1),y])
        L.append(d[x,(y+1)])
        
    #ligne du bas
    elif x == (a-1) and y != 0 : 
        L.append(d[(x-1),y])
        L.append(d[x,(y-1)])
        L.append(d[x,(y+1)])
    
    #ligne de droite
    elif x != 0 and y == (b-1) : 
        L.append(d[(x-1),y])
        L.append(d[x,(y-1)])
        L.append(d[(x+1),y])

    #cas général
    else :
        L.append(d[x,(y-1)])
        L.append(d[(x-1),y])
        L.append(d[x,(y+1)])
        L.append(d[(x+1),y])

    g = choice(L)
   
    return g
    

In [20]:
d

array([[ 1.,  0.,  0.,  3.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.],
       [ 1.,  3.,  0.,  0.,  3.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  2.],
       [ 0.,  1.,  0.,  0.,  3.,  0.,  1.,  0.,  3.,  1.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  3.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  3.,  1.,  1.,  2.,  0.,  0.]])

In [21]:
voisins(1,0)

1.0

In [22]:
voisins(2,3)

3.0

In [23]:
#On s'interesse aux voisins de chaque case
def voisins2(x,y) : 
    """Renvoie tous les voisins de (x,y) dans la matrice d en faisant attention aux coins/bords"""
    L = []
    CoordL=[]

    #coin supérieur gauche
    if x == 0 and y == 0 : 
        L.append(d[(x+1),y])
        CoordL.append(tuple([(x+1),y]))
        L.append(d[x,(y+1)])
        CoordL.append(tuple([x,(y+1)]))
    
    #coin supérieur droit
    elif x == 0 and y == (b-1) : 
        L.append(d[(x+1),y])
        CoordL.append(tuple([(x+1),y]))
        L.append(d[x,(y-1)])
        CoordL.append(tuple([x,(y-1)]))
    
    #coin inférieur gauche
    elif x == (a-1) and y == 0 : 
        L.append(d[x,(y+1)])
        CoordL.append(tuple([x,(y+1)]))
        L.append(d[(x-1),y])
        CoordL.append(tuple([(x-1),y]))
    
    #coin inférieur droit
    elif x == (a-1) and y == (b-1) :
        L.append(d[(x-1),y])
        CoordL.append(tuple([(x-1),y]))
        L.append(d[x,(y-1)])
        CoordL.append(tuple([x,(y-1)]))
    
    #ligne du haut
    elif x == 0 and y != 0:
        L.append(d[(x,(y-1))])
        CoordL.append(tuple([x,(y-1)]))
        L.append(d[(x+1),y])
        CoordL.append(tuple([(x+1),y]))
        L.append(d[x,(y+1)])
        CoordL.append(tuple([x,(y+1)]))
        
    #ligne de gauche
    elif x !=0 and y == 0 : 
        L.append(d[(x-1),y])
        CoordL.append(tuple([(x-1),y]))
        L.append(d[(x+1),y])
        CoordL.append(tuple([(x+1),y]))
        L.append(d[x,(y+1)])
        CoordL.append(tuple([x,(y+1)]))
        
    #ligne du bas
    elif x == (a-1) and y != 0 : 
        L.append(d[(x-1),y])
        CoordL.append(tuple([(x-1),y]))
        L.append(d[x,(y-1)])
        CoordL.append(tuple([x,(y-1)]))
        L.append(d[x,(y+1)])
        CoordL.append(tuple([x,(y+1)]))
    
    #ligne de droite
    elif x != 0 and y == (b-1) : 
        L.append(d[(x-1),y])
        CoordL.append(tuple([(x-1),y]))
        L.append(d[x,(y-1)])
        CoordL.append(tuple([x,(y-1)]))
        L.append(d[(x+1),y])
        CoordL.append(tuple([(x+1),y]))

    #cas général
    else :
        L.append(d[x,(y-1)])
        CoordL.append(tuple([x,(y-1)]))
        L.append(d[(x-1),y])
        CoordL.append(tuple([(x-1),y]))
        L.append(d[x,(y+1)])
        CoordL.append(tuple([x,(y+1)]))
        L.append(d[(x+1),y])
        CoordL.append(tuple([(x+1),y]))
   
    return L , CoordL
    

In [24]:
#On s'interesse aux voisins de chaque case
def voisins3(x,y) : 
    """Renvoie tous les voisins de (x,y) dans la matrice d en faisant attention aux coins/bords"""
    L = []
    CoordL=[]

    #coin supérieur gauche
    if x == 0 and y == 0 : 
        L.append(d[(x+1),y])
        CoordL.append(tuple([d[(x+1),y],((x+1),y)]))
        L.append(d[x,(y+1)])
        CoordL.append(tuple([d[x,(y+1)],(x,(y+1))]))
    
    #coin supérieur droit
    elif x == 0 and y == (b-1) : 
        L.append(d[(x+1),y])
        CoordL.append(tuple([d[(x+1),y],((x+1),y)]))
        L.append(d[x,(y-1)])
        CoordL.append(tuple([d[x,(y-1)],(x,(y-1))]))
    
    #coin inférieur gauche
    elif x == (a-1) and y == 0 : 
        L.append(d[x,(y+1)])
        CoordL.append(tuple([d[x,(y+1)],(x,(y+1))]))
        L.append(d[(x-1),y])
        CoordL.append(tuple([d[(x-1),y],((x-1),y)]))
    
    #coin inférieur droit
    elif x == (a-1) and y == (b-1) :
        L.append(d[(x-1),y])
        CoordL.append(tuple([d[(x-1),y],((x-1),y)]))
        L.append(d[x,(y-1)])
        CoordL.append(tuple([d[x,(y-1)],(x,(y-1))]))
    
    #ligne du haut
    elif x == 0 and y != 0:
        L.append(d[(x,(y-1))])
        CoordL.append(tuple([d[x,(y-1)],(x,(y-1))]))
        L.append(d[(x+1),y])
        CoordL.append(tuple([d[(x+1),y],((x+1),y)]))
        L.append(d[x,(y+1)])
        CoordL.append(tuple([d[x,(y+1)],(x,(y+1))]))
        
    #ligne de gauche
    elif x !=0 and y == 0 : 
        L.append(d[(x-1),y])
        CoordL.append(tuple([d[(x-1),y],((x-1),y)]))
        L.append(d[(x+1),y])
        CoordL.append(tuple([d[(x+1),y],((x+1),y)]))
        L.append(d[x,(y+1)])
        CoordL.append(tuple([d[x,(y+1)],(x,(y+1))]))
        
    #ligne du bas
    elif x == (a-1) and y != 0 : 
        L.append(d[(x-1),y])
        CoordL.append(tuple([d[(x-1),y],((x-1),y)]))
        L.append(d[x,(y-1)])
        CoordL.append(tuple([d[x,(y-1)],(x,(y-1))]))
        L.append(d[x,(y+1)])
        CoordL.append(tuple([d[x,(y+1)],(x,(y+1))]))
    
    #ligne de droite
    elif x != 0 and y == (b-1) : 
        L.append(d[(x-1),y])
        CoordL.append(tuple([d[(x-1),y],((x-1),y)]))
        L.append(d[x,(y-1)])
        CoordL.append(tuple([d[x,(y-1)],(x,(y-1))]))
        L.append(d[(x+1),y])
        CoordL.append(tuple([d[(x+1),y],((x+1),y)]))

    #cas général
    else :
        L.append(d[x,(y-1)])
        CoordL.append(tuple([d[x,(y-1)],(x,(y-1))]))
        L.append(d[(x-1),y])
        CoordL.append(tuple([d[(x-1),y],((x-1),y)]))
        L.append(d[x,(y+1)])
        CoordL.append(tuple([d[x,(y+1)],(x,(y+1))]))
        L.append(d[(x+1),y])
        CoordL.append(tuple([d[(x+1),y],((x+1),y)]))
   
    g = choice(CoordL)
    
    return g
    

In [25]:
voisins2(0,1)

([1.0, 2.0, 0.0], [(0, 0), (1, 1), (0, 2)])

In [26]:
len(np.where(d == 1.)[0])

48

In [27]:
c = len(np.where(d == 3.)[0])
c

8

In [28]:
n = d.size
n

100

In [29]:
#réguler le nombre de meutes de lionnes présents dans la matrice afin de stabiliser son nombre à 8%
while c > 0.08*n : 
    for k in range (0,a) :
        for i in range (0,b) :
            if d[k,i] == 3 : 
                d[k,i] = 0
            else :
                d[k,i] = 3


In [30]:
len(np.where(d == 3.)[0])

8

In [31]:
a

10

In [32]:
len(np.where(d == 3.)[0])

8

In [33]:
#On s'interesse maintenant aux interactions entre les gazelles et les lions/meutes de lionnes
#Pour l'instant on se met dans le cas ou dès lors qu'il y a rencontre entre gazelle et lion/meute de lionne, 
#la gazelle se fait attraper et elle fait donc place à une nouvelle case vide dont la valeur est 0
#On caractérise la rencontre en un lion/une lionne et une gazelle par le fait qu'ils soient voisins

In [34]:
d

array([[ 1.,  0.,  0.,  3.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.],
       [ 1.,  3.,  0.,  0.,  3.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  2.],
       [ 0.,  1.,  0.,  0.,  3.,  0.,  1.,  0.,  3.,  1.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  3.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  3.,  1.,  1.,  2.,  0.,  0.]])

In [35]:
#tout d'abord, on doit scanner entièrement la matrice pour se rendre 
#compte de la position de chaque élément : ensuite on peut passer à la rencontre entre les différents êtres dans la matrice 
def scan_matrice() :
    for k in range (0,a) :
        for i in range (0,b) :
            if (d[k,i]) == 1.:
                print ("gazelle,","coordonnées:",(k,i))
            elif (d[k,i]) == 2.:
                print ("lion,","coordonnées:",(k,i))
            if (d[k,i]) == 3.:
                print ("lionne,","coordonnées:",(k,i))
            else :
                print ("case vide,","coordonnées:",(k,i))
            print ("voisins :",voisins2(k,i))
            

In [36]:
scan_matrice()

gazelle, coordonnées: (0, 0)
case vide, coordonnées: (0, 0)
voisins : ([1.0, 0.0], [(1, 0), (0, 1)])
case vide, coordonnées: (0, 1)
voisins : ([1.0, 2.0, 0.0], [(0, 0), (1, 1), (0, 2)])
case vide, coordonnées: (0, 2)
voisins : ([0.0, 0.0, 3.0], [(0, 1), (1, 2), (0, 3)])
lionne, coordonnées: (0, 3)
voisins : ([0.0, 1.0, 0.0], [(0, 2), (1, 3), (0, 4)])
case vide, coordonnées: (0, 4)
voisins : ([3.0, 1.0, 1.0], [(0, 3), (1, 4), (0, 5)])
gazelle, coordonnées: (0, 5)
case vide, coordonnées: (0, 5)
voisins : ([0.0, 1.0, 1.0], [(0, 4), (1, 5), (0, 6)])
gazelle, coordonnées: (0, 6)
case vide, coordonnées: (0, 6)
voisins : ([1.0, 1.0, 1.0], [(0, 5), (1, 6), (0, 7)])
gazelle, coordonnées: (0, 7)
case vide, coordonnées: (0, 7)
voisins : ([1.0, 0.0, 1.0], [(0, 6), (1, 7), (0, 8)])
gazelle, coordonnées: (0, 8)
case vide, coordonnées: (0, 8)
voisins : ([1.0, 0.0, 1.0], [(0, 7), (1, 8), (0, 9)])
gazelle, coordonnées: (0, 9)
case vide, coordonnées: (0, 9)
voisins : ([1.0, 1.0], [(1, 9), (0, 8)])
gazel

In [37]:
voisins2(0,0)

([1.0, 0.0], [(1, 0), (0, 1)])

In [38]:
#premier passage des lions/meutes de lionnes sur les gazelles
def rencontre2():

    for k in range (0,a) : 
        for i in range (0,b) : 
            if d[k,i] == 1. :
                L = voisins(k,i)
                print(L)
                CoordL = voisins2(k,i)
                print(CoordL)
                while L != [] :
                    if L[0] == 2. :
                        d[k,i] = 2.
                        L.remove(L[0])
                        d[CoordL[0]] = 0.
                        CoordL.remove(CoordL[0])
                    if L[0] == 3. :
                        d[k,i] = 3.
                        L.remove(L[0])
                        d[CoordL[0]] = 0.
                        CoordL.remove(CoordL[0])
                    if L[0] == 0. :
                        d[k,i] = 0.
                        d[CoordL[0]] = 1.
                        CoordL.remove(CoordL[0])
                        
    return d
                        
            

In [39]:
#premier passage des lions/meutes de lionnes sur les gazelles
def rencontre():
    d
    for k in range (0,a) : 
        for i in range (0,b) : 
            g = voisins3(k,i)
            #print (g)
            if d[k,i] == 1. :
                    if g[0] == 2. :
                        d[k,i] = 2.
                        d[g[1]] = 0.
                    if g[0] == 3. :
                        d[k,i] = 3.
                        d[g[1]] = 0.
                    if g[0] == 0. :
                        d[k,i] = 0.
                        d[g[1]] = 1.

            elif d[k,i] == 2. :
                    if g == 1. :
                        d[k,i] = 0.
                        d[g[1]] = 2.
                    if g == 0. :
                        d[k,i] = 0.
                        d[g[1]] = 2.
                    
            
            elif d[k,i] == 3. :
                    if g == 1. :
                        d[k,i] = 0.
                        d[g[1]] = 3.
                    if g == 0. :
                        d[k,i] = 0.
                        d[g[1]] = 3.
                    
                        
    print("nombre de gazelles :",len(np.where(d == 1.)[0]))
    print("nombre de meutes de lionnes :",len(np.where(d == 2.)[0]))
    print("nombre de lions :",len(np.where(d == 3.)[0]))
    return d
                        
            

In [40]:
d

array([[ 1.,  0.,  0.,  3.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.],
       [ 1.,  3.,  0.,  0.,  3.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  2.],
       [ 0.,  1.,  0.,  0.,  3.,  0.,  1.,  0.,  3.,  1.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  3.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  3.,  1.,  1.,  2.,  0.,  0.]])

In [41]:
len(np.where(d == 1.)[0])

48

In [42]:
len(np.where(d == 2.)[0])

4

In [43]:
len(np.where(d == 3.)[0])

8

In [44]:
def boucle(jours) :
    for i in range (jours):
        rencontre()
        print(d)
    return d

In [45]:
boucle(10)

nombre de gazelles : 39
nombre de meutes de lionnes : 4
nombre de lions : 8
[[ 1.  0.  0.  3.  0.  1.  1.  1.  0.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 0.  3.  0.  0.  3.  0.  1.  0.  1.  2.]
 [ 2.  1.  1.  1.  0.  1.  1.  0.  3.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  3.  1.  1.  0.  3.  0.]
 [ 1.  0.  1.  0.  1.  1.  1.  0.  1.  1.]
 [ 0.  0.  3.  0.  0.  1.  0.  1.  0.  1.]
 [ 1.  1.  1.  0.  0.  0.  1.  0.  1.  1.]
 [ 0.  0.  1.  3.  0.  2.  2.  0.  0.  0.]]
nombre de gazelles : 35
nombre de meutes de lionnes : 4
nombre de lions : 8
[[ 0.  0.  0.  3.  1.  1.  1.  1.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  3.  1.  0.  1.  2.  0.]
 [ 2.  0.  1.  1.  1.  0.  1.  0.  3.  0.]
 [ 0.  3.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  1.  1.  0.  3.  1.]
 [ 1.  1.  0.  0.  3.  1.  1.  0.  1.  0.]
 [ 1.  1.  3.  0.  0.  0.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  1.  1.  1.  0.]
 [ 0.  1.  0.  3.  0.  2.  2. 

array([[ 0.,  0.,  3.,  0.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  0.,  1.,  0.,  3.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  3.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  3.,  1.,  0.,  3.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  1.,  0.],
       [ 0.,  0.,  3.,  3.,  0.,  2.,  0.,  0.,  0.,  0.]])